// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0kRyQX4PWYh_n_Uo76EToQ--ipr0h-c',
    appId: '1:165908157732:web:65fa35bc371935aa948fb1',
    messagingSenderId: '165908157732',
    projectId: 'hostelmanagement-5845d',
    authDomain: 'hostelmanagement-5845d.firebaseapp.com',
    storageBucket: 'hostelmanagement-5845d.firebasestorage.app',
    measurementId: 'G-EJMSFHKWRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYkKauE22P0CYtm6WZUz0fJaqWYbIi8tk',
    appId: '1:165908157732:android:13a0932edb9f2e42948fb1',
    messagingSenderId: '165908157732',
    projectId: 'hostelmanagement-5845d',
    storageBucket: 'hostelmanagement-5845d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSPS-v3wteLfrWRDbw7SoSFH73Z-RVkEw',
    appId: '1:165908157732:ios:fa4e4064da92f7b3948fb1',
    messagingSenderId: '165908157732',
    projectId: 'hostelmanagement-5845d',
    storageBucket: 'hostelmanagement-5845d.firebasestorage.app',
    iosBundleId: 'com.example.hostelmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSPS-v3wteLfrWRDbw7SoSFH73Z-RVkEw',
    appId: '1:165908157732:ios:fa4e4064da92f7b3948fb1',
    messagingSenderId: '165908157732',
    projectId: 'hostelmanagement-5845d',
    storageBucket: 'hostelmanagement-5845d.firebasestorage.app',
    iosBundleId: 'com.example.hostelmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD0kRyQX4PWYh_n_Uo76EToQ--ipr0h-c',
    appId: '1:165908157732:web:4f2fe7c2406fe80f948fb1',
    messagingSenderId: '165908157732',
    projectId: 'hostelmanagement-5845d',
    authDomain: 'hostelmanagement-5845d.firebaseapp.com',
    storageBucket: 'hostelmanagement-5845d.firebasestorage.app',
    measurementId: 'G-V56PTNX8XQ',
  );
}
